### ISSUE TITLE
Remove dependency on PSR-7

### ISSUE THREAD

**Issue by samdark** [yiisoft/http#11]
Currently this package is almost PSR-independent. The only place where PSR is used is `HeaderHelper::getSortedAcceptTypesFromRequest(RequestInterface $request)` and it likely worth removing this method.

**Comment by xepozz** [comment]
Why did you want to remove that method? Because it needed psr-package dependency?
I don't think that it's a problem.

**Comment by samdark** [comment]
It's not a problem per se, just an odd reason to have a dependency.

**Comment by samdark** [comment]
Let's remove `getSortedAcceptTypesFromRequest()` and use the following instead:

```php
$acceptTypes = HeaderHelper::getSortedAcceptTypes($request->getHeader('accept'));
```

**Comment by samdark** [comment]
If we'll need dependency later, we'll add it.
