### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by xepozz** [yiisoft/http#5]
I think would be nice to have an additional helper `Header`, like these https://github.com/yiisoft/http/blob/master/src/Method.php or https://github.com/yiisoft/http/blob/master/src/Status.php.

List of all headers we will found on wiki https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

Also it should have `compare` and `find` methods and also the same methods with case-insensetive mode

**Comment by samdark** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers

**Comment by samdark** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add headers parsing to HTTP package](https://trello.com/c/6pofY02L/5-add-headers-parsing-to-http-package)
